### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by PierreDurrr** [mza921/plex2trakt#12]
Would this be updated to work with python3 ?

**Comment by PierreDurrr** [comment]
EDIT : just found your python3 branch, but got this error while trying to use it :

```
root@scripts:/scripts/crotte# python3 plex2trakt.py plex
Traceback (most recent call last):
  File "plex2trakt.py", line 9, in <module>
    from trakt import Trakt
  File "/scripts/crotte/trakt.py", line 40
    print 'Go to %(verification_url)s and enter %(user_code)s' % r.json()
                                                             ^
SyntaxError: invalid syntax
```
